/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class JFCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public JFCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPMenu = new javax.swing.JPanel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jTPantalla = new javax.swing.JTextField();
        jB0 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBSumar = new javax.swing.JButton();
        jBRestar = new javax.swing.JButton();
        jBMultiplicar = new javax.swing.JButton();
        jBDividir = new javax.swing.JButton();
        jBResto = new javax.swing.JButton();
        jBRBorrar = new javax.swing.JButton();
        jBRResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(212, 190));
        setMinimumSize(new java.awt.Dimension(212, 190));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(212, 190));

        jPanel1.setBackground(new java.awt.Color(36, 37, 42));
        jPanel1.setMaximumSize(new java.awt.Dimension(212, 240));
        jPanel1.setMinimumSize(new java.awt.Dimension(212, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(212, 240));

        jPMenu.setBackground(new java.awt.Color(44, 130, 201));
        jPMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculadora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPMenu.setForeground(new java.awt.Color(129, 207, 224));
        jPMenu.setMaximumSize(new java.awt.Dimension(212, 40));
        jPMenu.setMinimumSize(new java.awt.Dimension(212, 40));
        jPMenu.setPreferredSize(new java.awt.Dimension(212, 40));

        jLMinimizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLMinimizar.setForeground(new java.awt.Color(0, 0, 255));
        jLMinimizar.setText("-");
        jLMinimizar.setToolTipText("");
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseClicked(evt);
            }
        });

        jLCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCerrar.setForeground(new java.awt.Color(255, 0, 0));
        jLCerrar.setText("X");
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jLMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCerrar)
                    .addComponent(jLMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPantalla.setEditable(false);
        jTPantalla.setBackground(new java.awt.Color(1, 50, 67));
        jTPantalla.setForeground(new java.awt.Color(255, 255, 255));
        jTPantalla.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTPantalla.setMaximumSize(new java.awt.Dimension(61, 20));
        jTPantalla.setMinimumSize(new java.awt.Dimension(61, 20));

        jB0.setBackground(new java.awt.Color(1, 50, 67));
        jB0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB0.setForeground(new java.awt.Color(129, 207, 224));
        jB0.setText("0");
        jB0.setBorder(null);
        jB0.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB0ActionPerformed(evt);
            }
        });

        jB1.setBackground(new java.awt.Color(1, 50, 67));
        jB1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB1.setForeground(new java.awt.Color(129, 207, 224));
        jB1.setText("1");
        jB1.setBorder(null);
        jB1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setBackground(new java.awt.Color(1, 50, 67));
        jB2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB2.setForeground(new java.awt.Color(129, 207, 224));
        jB2.setText("2");
        jB2.setBorder(null);
        jB2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setBackground(new java.awt.Color(1, 50, 67));
        jB3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB3.setForeground(new java.awt.Color(129, 207, 224));
        jB3.setText("3");
        jB3.setBorder(null);
        jB3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB3ActionPerformed(evt);
            }
        });

        jB4.setBackground(new java.awt.Color(1, 50, 67));
        jB4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB4.setForeground(new java.awt.Color(129, 207, 224));
        jB4.setText("4");
        jB4.setBorder(null);
        jB4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setBackground(new java.awt.Color(1, 50, 67));
        jB5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB5.setForeground(new java.awt.Color(129, 207, 224));
        jB5.setText("5");
        jB5.setBorder(null);
        jB5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setBackground(new java.awt.Color(1, 50, 67));
        jB6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB6.setForeground(new java.awt.Color(129, 207, 224));
        jB6.setText("6");
        jB6.setBorder(null);
        jB6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB6ActionPerformed(evt);
            }
        });

        jB7.setBackground(new java.awt.Color(1, 50, 67));
        jB7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB7.setForeground(new java.awt.Color(129, 207, 224));
        jB7.setText("7");
        jB7.setBorder(null);
        jB7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setBackground(new java.awt.Color(1, 50, 67));
        jB8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB8.setForeground(new java.awt.Color(129, 207, 224));
        jB8.setText("8");
        jB8.setBorder(null);
        jB8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setBackground(new java.awt.Color(1, 50, 67));
        jB9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB9.setForeground(new java.awt.Color(129, 207, 224));
        jB9.setText("9");
        jB9.setBorder(null);
        jB9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jB9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB9ActionPerformed(evt);
            }
        });

        jBSumar.setBackground(new java.awt.Color(1, 50, 67));
        jBSumar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBSumar.setForeground(new java.awt.Color(129, 207, 224));
        jBSumar.setText("+");
        jBSumar.setBorder(null);
        jBSumar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBSumar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBSumarActionPerformed(evt);
            }
        });

        jBRestar.setBackground(new java.awt.Color(1, 50, 67));
        jBRestar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRestar.setForeground(new java.awt.Color(129, 207, 224));
        jBRestar.setText("-");
        jBRestar.setBorder(null);
        jBRestar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBRestar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBRestarActionPerformed(evt);
            }
        });

        jBMultiplicar.setBackground(new java.awt.Color(1, 50, 67));
        jBMultiplicar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBMultiplicar.setForeground(new java.awt.Color(129, 207, 224));
        jBMultiplicar.setText("*");
        jBMultiplicar.setBorder(null);
        jBMultiplicar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBMultiplicar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBMultiplicarActionPerformed(evt);
            }
        });

        jBDividir.setBackground(new java.awt.Color(1, 50, 67));
        jBDividir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBDividir.setForeground(new java.awt.Color(129, 207, 224));
        jBDividir.setText("/");
        jBDividir.setBorder(null);
        jBDividir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBDividir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBDividirActionPerformed(evt);
            }
        });

        jBResto.setBackground(new java.awt.Color(1, 50, 67));
        jBResto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBResto.setForeground(new java.awt.Color(129, 207, 224));
        jBResto.setText("%");
        jBResto.setBorder(null);
        jBResto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBResto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBRestoActionPerformed(evt);
            }
        });

        jBRBorrar.setBackground(new java.awt.Color(1, 50, 67));
        jBRBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRBorrar.setForeground(new java.awt.Color(129, 207, 224));
        jBRBorrar.setText("AC");
        jBRBorrar.setBorder(null);
        jBRBorrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBRBorrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBRBorrarActionPerformed(evt);
            }
        });

        jBRResultado.setBackground(new java.awt.Color(1, 50, 67));
        jBRResultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRResultado.setForeground(new java.awt.Color(129, 207, 224));
        jBRResultado.setText("=");
        jBRResultado.setBorder(null);
        jBRResultado.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBRResultado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBRResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBRResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBRBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBResto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB7)
                    .addComponent(jB8)
                    .addComponent(jB9)
                    .addComponent(jBSumar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB4)
                    .addComponent(jB5)
                    .addComponent(jB6)
                    .addComponent(jBRestar)
                    .addComponent(jBResto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1)
                    .addComponent(jB2)
                    .addComponent(jB3)
                    .addComponent(jBMultiplicar)
                    .addComponent(jBRBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB0)
                    .addComponent(jBRResultado)
                    .addComponent(jBDividir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizarMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB0ActionPerformed
    {//GEN-HEADEREND:event_jB0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB0ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB1ActionPerformed
    {//GEN-HEADEREND:event_jB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB2ActionPerformed
    {//GEN-HEADEREND:event_jB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB3ActionPerformed
    {//GEN-HEADEREND:event_jB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB4ActionPerformed
    {//GEN-HEADEREND:event_jB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB5ActionPerformed
    {//GEN-HEADEREND:event_jB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB6ActionPerformed
    {//GEN-HEADEREND:event_jB6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB7ActionPerformed
    {//GEN-HEADEREND:event_jB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB8ActionPerformed
    {//GEN-HEADEREND:event_jB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB9ActionPerformed
    {//GEN-HEADEREND:event_jB9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB9ActionPerformed

    private void jBRResultadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBRResultadoActionPerformed
    {//GEN-HEADEREND:event_jBRResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRResultadoActionPerformed

    private void jBRBorrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBRBorrarActionPerformed
    {//GEN-HEADEREND:event_jBRBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRBorrarActionPerformed

    private void jBRestarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBRestarActionPerformed
    {//GEN-HEADEREND:event_jBRestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRestarActionPerformed

    private void jBSumarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSumarActionPerformed
    {//GEN-HEADEREND:event_jBSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSumarActionPerformed

    private void jBDividirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBDividirActionPerformed
    {//GEN-HEADEREND:event_jBDividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDividirActionPerformed

    private void jBMultiplicarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBMultiplicarActionPerformed
    {//GEN-HEADEREND:event_jBMultiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBMultiplicarActionPerformed

    private void jBRestoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBRestoActionPerformed
    {//GEN-HEADEREND:event_jBRestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRestoActionPerformed

    public JButton getjB0()
    {
        return jB0;
    }

    public JButton getjB1()
    {
        return jB1;
    }

    public JButton getjB2()
    {
        return jB2;
    }

    public JButton getjB3()
    {
        return jB3;
    }

    public JButton getjB4()
    {
        return jB4;
    }

    public JButton getjB5()
    {
        return jB5;
    }

    public JButton getjB6()
    {
        return jB6;
    }

    public JButton getjB7()
    {
        return jB7;
    }

    public JButton getjB8()
    {
        return jB8;
    }

    public JButton getjB9()
    {
        return jB9;
    }

    public JButton getjBDividir()
    {
        return jBDividir;
    }

    public JButton getjBMultiplicar()
    {
        return jBMultiplicar;
    }

    public JButton getjBRBorrar()
    {
        return jBRBorrar;
    }

    public JButton getjBRResultado()
    {
        return jBRResultado;
    }

    public JButton getjBRestar()
    {
        return jBRestar;
    }

    public JButton getjBResto()
    {
        return jBResto;
    }

    public JButton getjBSumar()
    {
        return jBSumar;
    }

    public JTextField getjTPantalla()
    {
        return jTPantalla;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBDividir;
    private javax.swing.JButton jBMultiplicar;
    private javax.swing.JButton jBRBorrar;
    private javax.swing.JButton jBRResultado;
    private javax.swing.JButton jBRestar;
    private javax.swing.JButton jBResto;
    private javax.swing.JButton jBSumar;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTPantalla;
    // End of variables declaration//GEN-END:variables
}
